name: remote ssh command
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            pm2 delete clashverse --silent
            cd clashverse
            git reset --hard HEAD
            git clean -f -d
            git pull
            pm2 start bot.py --interpreter=./venv/bin/python --name clashverse
